# Generated by Django 4.2.4 on 2023-09-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_num',
            field=models.IntegerField(),
        ),
    ]
