# Generated by Django 4.2.4 on 2023-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_student_roll_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
